weights: /project/yolo_results/exp16/weights/last.pt
cfg: ''
data: datadef/airbus_kaggle_aiqu.yaml
hyp: yolov5/data/hyps/hyp.scratch-low.yaml
epochs: 85
batch_size: 256
imgsz: 768
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: 0,1
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /project/yolo_results
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: 10
local_rank: 1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /project/yolo_results/exp16
